services:
  server:
    image: itzg/minecraft-server:java25@sha256:bf0ca4aad9cf56c6c59cfb4087cd5e0fea4957a0ff989119a504f9abc80fb6ee
    restart: on-failure
    user: '1000:1000'
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "26.2"
      SEED: "-5448382977646654394"
      RCON_CMDS_STARTUP:  |-
        /gamerule mobGriefing false
        /gamerule keepInventory true
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://github.com/ViaVersion/ViaVersion/releases/download/5.11.0/ViaVersion-5.11.0.jar
    ports:
      - 35565:25565
      - 29132:19132/udp
    volumes:
      - ${APP_DATA_DIR}/data:/data
    stdin_open: true
    tty: true