services:
  server:
    image: itzg/minecraft-server:java21@sha256:40f9b9b6e64589a90ddfce3062b3b2f207d59fa1ecd588c2b57c2e04e4500c20
    restart: on-failure
    user: '1000:1000'
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21.10"
      SEED: "-5448382977646654394"
      RCON_CMDS_STARTUP:  |-
        /gamerule mobGriefing false
        /gamerule keepInventory true
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://github.com/ViaVersion/ViaVersion/releases/download/5.6.0/ViaVersion-5.6.0.jar
    ports:
      - 35565:25565
      - 29132:19132/udp
    volumes:
      - ${APP_DATA_DIR}/data:/data
    stdin_open: true
    tty: true