services:
  server:
    image: arm64v8/nginx:1.29.1@sha256:e041cf856a0f3790b5ef37a966f43d872fba48fcf4405fd3e8a28ac5f7436992
    ports:
      - 35575:80
    volumes:
      - ${APP_DATA_DIR}/html:/usr/share/nginx/html:ro
    restart: on-failure